apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: axum-web-preview-environments
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: therustdeveloper
        repo: axum-web
        tokenRef:
          secretName: gh-therustdeveloper
          key: password
        labels:
        - preview
      requeueAfterSeconds: 15
  template:      
    metadata:
      name: '{{head_short_sha}}-{{number}}-preview' # 'axum-web-{{branch_slug}}-{{number}}'
    spec:
      source:
        repoURL: https://github.com/therustdeveloper/axum-web.git
        targetRevision: '{{head_short_sha}}'
        path: helm
        helm:
          parameters:
          - name: "image.tag"
            value: '{{head_sha}}'
          - name: "namespace"
            value: '{{head_short_sha}}-{{number}}-preview' # 'axum-web-{{branch_slug}}-{{number}}'
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{head_short_sha}}-{{number}}-preview' # 'axum-web-{{branch_slug}}-{{number}}'
      
      
