apiVersion: apps/v1
kind: Deployment
metadata:
  name: axum-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "hachikoapp/axum-web:{{ default .Chart.Version .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}