replicaCount: 1
name: axum-web
env: staging
namespace: staging
image:
  name: webserver-simple # image name change automatically
  tag: 'a9f44751c23820745efef75e7a053b3ed8da6f8a' # tag change automatically
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 3000
  portName: http
