replicaCount: 1
name: axum-web
env: staging
namespace: staging
image:
  name: hachikoapp/axum-web # image name change automatically
  tag: '4.0.0' # tag change automatically
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8418
  targetPort: 3000
  portName: http
